defmodule PureAdmin.Components.Document do
  @moduledoc """
  Word-style hierarchical numbered document (`pa-document`).

  Nest `document_section/1` inside one another and the outline number
  (`1`, `1.1`, `1.1.1` …) is generated by CSS counters — you never write it, so
  reordering or inserting a section renumbers everything automatically (up to six
  levels deep). Put body copy in `document_text/1`; any other content (tables,
  callouts) can sit between the heading and the nested sections without disturbing
  the numbering. Set `is_manual` to write your own numbers (appendices, `A` / `A.1`).
  """
  use Phoenix.Component

  import PureAdmin.Helpers

  @doc """
  The document container.

  ## Examples

      <.document>
        <.document_section heading="Introduction">
          <.document_text>Top-level section — renders as "1 Introduction".</.document_text>

          <.document_section heading="Scope" level={3}>
            <.document_text>Nested — renders as "1.1 Scope".</.document_text>
          </.document_section>
        </.document_section>

        <.document_section heading="Architecture">
          <.document_text>Renders as "2 Architecture".</.document_text>
        </.document_section>
      </.document>

  Manual numbering (appendix scheme):

      <.document is_manual>
        <.document_section heading="Appendix" number="A" level={2}>
          <.document_section heading="Glossary" number="A.1" level={3} />
        </.document_section>
      </.document>
  """
  attr(:is_manual, :boolean,
    default: false,
    doc:
      "Author-written numbers (emits `pa-document--manual`); the CSS auto-number is disabled — supply each number via `number` on document_section/1."
  )

  attr(:density, :string,
    default: nil,
    values: [nil, "compact", "spacious"],
    doc: "Vertical rhythm between sections (`pa-document--compact` / `--spacious`)."
  )

  attr(:is_flush, :boolean,
    default: false,
    doc: "Drop the per-level indentation (`pa-document--flush`); the number chain conveys hierarchy."
  )

  attr(:class, :string, default: nil)
  attr(:rest, :global)
  slot(:inner_block, required: true)

  def document(assigns) do
    ~H"""
    <div class={document_classes(assigns)} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  defp document_classes(assigns) do
    build_classes(
      "pa-document",
      [
        {"pa-document--manual", assigns.is_manual},
        {"pa-document--#{assigns.density}", assigns.density != nil},
        {"pa-document--flush", assigns.is_flush}
      ],
      assigns.class
    )
  end

  @doc """
  A numbered section. Nest sections inside sections for sub-numbering (`1.1`, `1.1.1`).

  Set `level` to the heading tag matching the nesting depth (2 for top-level, 3 for
  the next, …) for correct document semantics — styling is depth-driven by CSS, so
  the level is about accessibility, not size.
  """
  attr(:heading, :string,
    default: nil,
    doc: "Heading text (rendered in `.pa-document__heading`). Omit for a section that is only a wrapper."
  )

  attr(:level, :integer,
    default: 2,
    values: [2, 3, 4, 5, 6],
    doc: "Heading tag level (h2…h6). Set it to match the nesting depth."
  )

  attr(:number, :string,
    default: nil,
    doc: "Manual number (only meaningful when the container has `is_manual`), e.g. \"A\" / \"A.1\"."
  )

  attr(:class, :string, default: nil)
  attr(:rest, :global)

  slot(:inner_block,
    required: true,
    doc: "Section body: `document_text/1` paragraphs, other content, and nested `document_section/1`."
  )

  def document_section(assigns) do
    ~H"""
    <section class={build_classes("pa-document__section", [], @class)} {@rest}>
      <.dynamic_tag :if={@heading} tag_name={"h#{@level}"} class="pa-document__heading"><span
          :if={@number}
          class="pa-document__number"
        >{@number}</span>{@heading}</.dynamic_tag>
      {render_slot(@inner_block)}
    </section>
    """
  end

  @doc """
  A body paragraph inside a section (`.pa-document__text`).
  """
  attr(:class, :string, default: nil)
  attr(:rest, :global)
  slot(:inner_block, required: true)

  def document_text(assigns) do
    ~H"""
    <p class={build_classes("pa-document__text", [], @class)} {@rest}>
      {render_slot(@inner_block)}
    </p>
    """
  end
end
