defmodule DemoWeb.Live.SheetLive do
  @moduledoc """
  Demo for the `pa-sheet` component (printable A4 document shell).
  Mirrors `pure-admin/demo/views/sheet.mustache` using keen wrapper components —
  a representative gridded tax invoice with isolated single-element printing.
  """
  use DemoWeb, :live_view

  def mount(_params, _session, socket) do
    {:ok, assign(socket, page_title: "Sheet")}
  end

  def render(assigns) do
    ~H"""
    <.paragraph>
      <code>pa-sheet</code>
      is a centred, A4-width white "paper" page for invoices, orders, quotes, receipts and
      delivery notes. It prints ink-on-white by default; use the print button
      (<code>sheet_print_button/1</code>, backed by the <code>PureAdminSheetPrint</code> hook) to
      print a single sheet in isolation via a hidden iframe — no page-level print CSS needed.
    </.paragraph>

    <%!-- A realistic tax invoice --%>
    <.card title_text="Tax invoice">
      <.sheet id="inv-142">
        <.sheet_masthead is_ruled doctitle="INVOICE No. 2026-0142" docmeta="Tax invoice">
          <:brand>Twin Peaks Ltd.</:brand>
        </.sheet_masthead>

        <.sheet_parties>
          <.sheet_party label="Supplier" name="Twin Peaks Ltd." variant="boxed">
            221B Baker Street<br />London NW1 6XE<br />United Kingdom
            <.fields is_horizontal is_compact is_no_border class="mt-2">
              <.field label="Reg. No.">12345678</.field>
              <.field label="VAT">GB123456789</.field>
            </.fields>
          </.sheet_party>
          <.sheet_party label="Bill to" name="Northwind GmbH" variant="boxed">
            Musterstraße 1<br />10115 Berlin<br />Germany
            <.fields is_horizontal is_compact is_no_border class="mt-2">
              <.field label="VAT">DE987654321</.field>
            </.fields>
          </.sheet_party>
        </.sheet_parties>

        <.sheet_meta is_boxed>
          <.sheet_meta_row label="Reference No.">2071845390</.sheet_meta_row>
          <.sheet_meta_row label="Issue date">Sep 9, 2026</.sheet_meta_row>
          <.sheet_meta_row label="Due date">Sep 23, 2026</.sheet_meta_row>
          <.sheet_meta_row label="Payment">Bank transfer</.sheet_meta_row>
        </.sheet_meta>

        <div class="pa-table-container">
          <table class="pa-table pa-table--bordered">
            <thead>
              <tr>
                <th>Description</th>
                <th class="text-end">Qty</th>
                <th class="text-end">Unit price</th>
                <th class="text-end">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <span class="pa-table__item-title">Application support</span>
                  <span class="pa-table__item-desc">Business portal — August 2026</span>
                </td>
                <td class="text-end">5 days</td>
                <td class="text-end">8,000.00</td>
                <td class="text-end">40,000.00</td>
              </tr>
              <tr>
                <td>
                  <span class="pa-table__item-title">Infrastructure</span>
                  <span class="pa-table__item-desc">Managed hosting — August 2026</span>
                </td>
                <td class="text-end">1 mo</td>
                <td class="text-end">40,000.00</td>
                <td class="text-end">40,000.00</td>
              </tr>
            </tbody>
          </table>
        </div>

        <.sheet_totals>
          <.sheet_total_row label="Subtotal">80,000.00</.sheet_total_row>
          <.sheet_total_row label="VAT (0%)">0.00</.sheet_total_row>
          <.sheet_total_row label="Total due" is_grand>€80,000.00</.sheet_total_row>
        </.sheet_totals>

        <.sheet_notes>
          <p>
            Please settle by the due date. Interest on late payment is charged at the statutory rate.
            Thank you for your business.
          </p>
        </.sheet_notes>

        <.sheet_footer>
          <.sheet_signatures>
            <.sheet_sign label="Issued by" />
            <.sheet_sign label="Received by" />
          </.sheet_signatures>
          <.sheet_legal>
            Registered in the Commercial Register, Section C, File 12345 · Generated by an accounting system.
          </.sheet_legal>
          <.sheet_pageno>1 / 1</.sheet_pageno>
        </.sheet_footer>

        <div data-print-omit class="mt-4 text-end">
          <.sheet_print_button id="inv-142-print" title="Invoice 2026-0142">Print this invoice</.sheet_print_button>
        </div>
      </.sheet>
    </.card>

    <%!-- Modifier reference --%>
    <.card title_text="Modifiers">
      <.basic_list>
        <li>
          <code>density="compact" | "spacious"</code>
          — page density.
        </li>
        <li><code>is_framed</code> — hairline outer border.</li>
        <li><code>is_fluid</code> — drop the A4 max-width (embedded previews).</li>
        <li><code>is_fill</code> — full A4-height page, footer pinned to the bottom (short docs only).</li>
        <li><code>is_landscape</code> — A4 landscape for wide tables (print it individually).</li>
        <li>
          <code>print_mode="color" | "grayscale"</code>
          — keep theme colours / desaturate them on paper (default is ink-on-white).
        </li>
      </.basic_list>
    </.card>
    """
  end
end
